openapi: 3.1.0
info:
  title: Slido Clone API
  description: API specification for a Slido clone application (Forum Discussion Interactive).
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api/v1'
    description: Development server

tags:
  - name: User
    description: User authentication and registration
  - name: Room
    description: Room management
  - name: Participant
    description: Participant operations
  - name: Message
    description: Live chat messages
  - name: Leaderboard
    description: XP ranking and leaderboard

paths:
  /users/register:
    post:
      tags:
        - User
      summary: Register a new presenter
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseWrapper'
        '400':
          description: Invalid request body
        '409':
          description: Email or username already in use

  /users/login:
    post:
      tags:
        - User
      summary: Login user
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseWrapper'
        '401':
          description: Invalid credentials

  /users/anonymous:
    post:
      tags:
        - User
      summary: Anonymous join to a room
      operationId: anonymousJoin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnonymousUserRequest'
      responses:
        '200':
          description: Anonymous join successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JoinRoomResponseWrapper'
        '400':
          description: Room is closed or invalid request
        '404':
          description: Room not found

  /rooms:
    post:
      tags:
        - Room
      summary: Create a new room
      operationId: createRoom
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoomRequest'
      responses:
        '201':
          description: Room created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoomResponseWrapper'
        '400':
          description: Invalid request body

  /rooms/my-rooms:
    get:
      tags:
        - Room
      summary: Get rooms owned by presenter
      operationId: getMyRooms
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of rooms
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomListResponseWrapper'

  /rooms/{room_code}:
    get:
      tags:
        - Room
      summary: Get room detail by room code
      operationId: getRoomDetail
      parameters:
        - name: room_code
          in: path
          required: true
          schema:
            type: string
            minLength: 6
            maxLength: 6
      responses:
        '200':
          description: Room detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDetailResponseWrapper'
        '404':
          description: Room not found

  /rooms/{room_id}/close:
    patch:
      tags:
        - Room
      summary: Close a room
      operationId: closeRoom
      security:
        - bearerAuth: []
      parameters:
        - name: room_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloseRoomRequest'
      responses:
        '200':
          description: Room closed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateToCloseRoomWrapper'
        '404':
          description: Room not found

  /rooms/{room_code}/join:
    post:
      tags:
        - Participant
      summary: Join a room
      operationId: joinRoom
      security:
        - bearerAuth: []
      parameters:
        - name: room_code
          in: path
          required: true
          schema:
            type: string
            minLength: 6
            maxLength: 6
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JoinRoomRequest'
      responses:
        '200':
          description: Joined room successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JoinRoomResponseWrapper'
        '400':
          description: Room is closed or invalid request
        '404':
          description: Room not found

  /rooms/{room_id}/participants:
    get:
      tags:
        - Participant
      summary: Get participants list
      operationId: getParticipants
      security:
        - bearerAuth: []
      parameters:
        - name: room_id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 10
            maximum: 100
      responses:
        '200':
          description: List of participants
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantListResponseWrapper'

  /rooms/{room_id}/messages:
    post:
      tags:
        - Message
      summary: Send a message
      operationId: sendMessage
      security:
        - bearerAuth: []
      parameters:
        - name: room_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponseWrapper'
    get:
      tags:
        - Message
      summary: Get messages
      operationId: getMessages
      security:
        - bearerAuth: []
      parameters:
        - name: room_id
          in: path
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: before
          in: query
          description: Unix timestamp for cursor-based pagination
          schema:
            type: integer
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageListResponseWrapper'

  /rooms/{room_id}/leaderboard:
    get:
      tags:
        - Leaderboard
      summary: Get leaderboard
      operationId: getLeaderboard
      security:
        - bearerAuth: []
      parameters:
        - name: room_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Leaderboard data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaderboardResponseWrapper'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # Request Schemas
    RegisterUserRequest:
      type: object
      required:
        - username
        - email
        - password
        - role
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 30
        email:
          type: string
          format: email
          maxLength: 255
        password:
          type: string
          minLength: 8
          maxLength: 100
        role:
          type: string
          enum: [presenter, admin]

    LoginUserRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          maxLength: 100
        password:
          type: string
          maxLength: 100

    AnonymousUserRequest:
      type: object
      required:
        - room_code
        - display_name
      properties:
        room_code:
          type: string
          minLength: 6
          maxLength: 6
        display_name:
          type: string
          minLength: 3
          maxLength: 30

    CreateRoomRequest:
      type: object
      required:
        - title
        - presenter_id
      properties:
        title:
          type: string
          minLength: 3
          maxLength: 255
        presenter_id:
          type: integer

    CloseRoomRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [closed]

    JoinRoomRequest:
      type: object
      required:
        - username
        - room_code
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 30
        display_name:
          type: string
          minLength: 2
          maxLength: 100
        room_code:
          type: string
          minLength: 6
          maxLength: 6

    SendMessageRequest:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          minLength: 1
          maxLength: 1000

    # Response Schemas
    UserResponse:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        role:
          type: string
        created_at:
          type: string
          format: date-time

    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserResponse'
        token:
          type: string

    AuthResponseWrapper:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/AuthResponse'

    ParticipantResponse:
      type: object
      properties:
        id:
          type: integer
        room_id:
          type: integer
        display_name:
          type: string
        xp_score:
          type: integer
        is_anonymous:
          type: boolean
        joined_at:
          type: string
          format: date-time

    JoinRoomResponse:
      type: object
      properties:
        participant:
          $ref: '#/components/schemas/ParticipantResponse'
        token:
          type: string

    JoinRoomResponseWrapper:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/JoinRoomResponse'

    RoomResponse:
      type: object
      properties:
        id:
          type: integer
        room_code:
          type: string
        title:
          type: string
        presenter_id:
          type: integer
        status:
          type: string
        created_at:
          type: string
          format: date-time
        closed_at:
          type: string
          format: date-time
          nullable: true

    CreateRoomResponse:
      type: object
      properties:
        room:
          $ref: '#/components/schemas/RoomResponse'
        participant_id:
          type: integer

    CreateRoomResponseWrapper:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/CreateRoomResponse'

    PresenterInfo:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string

    RoomStats:
      type: object
      properties:
        total_participants:
          type: integer
        total_questions:
          type: integer
        total_polls:
          type: integer
        active_poll_id:
          type: integer
          nullable: true

    RoomDetailResponse:
      type: object
      properties:
        id:
          type: integer
        room_code:
          type: string
        title:
          type: string
        status:
          type: string
        presenter:
          $ref: '#/components/schemas/PresenterInfo'
        stats:
          $ref: '#/components/schemas/RoomStats'
        created_at:
          type: string
          format: date-time

    RoomDetailResponseWrapper:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/RoomDetailResponse'

    UpdateToCloseRoom:
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
        closed_at:
          type: string
          format: date-time

    UpdateToCloseRoomWrapper:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/UpdateToCloseRoom'

    RoomListItem:
      type: object
      properties:
        id:
          type: integer
        room_code:
          type: string
        title:
          type: string
        status:
          type: string
        participants_count:
          type: integer
        created_at:
          type: string
          format: date-time

    RoomListResponse:
      type: object
      properties:
        rooms:
          type: array
          items:
            $ref: '#/components/schemas/RoomListItem'

    RoomListResponseWrapper:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/RoomListResponse'

    ParticipantListItem:
      type: object
      properties:
        id:
          type: integer
        display_name:
          type: string
        xp_score:
          type: integer
        is_anonymous:
          type: boolean

    ParticipantListResponse:
      type: object
      properties:
        participants:
          type: array
          items:
            $ref: '#/components/schemas/ParticipantListItem'

    ParticipantListResponseWrapper:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ParticipantListResponse'
        paging:
          $ref: '#/components/schemas/PaginationResponse'

    PaginationResponse:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        total_item:
          type: integer
        total_page:
          type: integer

    ParticipantInfo:
      type: object
      properties:
        id:
          type: integer
        display_name:
          type: string

    MessageResponse:
      type: object
      properties:
        id:
          type: integer
        room_id:
          type: integer
        participant:
          $ref: '#/components/schemas/ParticipantInfo'
        content:
          type: string
        created_at:
          type: string
          format: date-time

    MessageResponseWrapper:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/MessageResponse'

    MessageListResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MessageResponse'
        has_more:
          type: boolean

    MessageListResponseWrapper:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/MessageListResponse'

    LeaderboardEntry:
      type: object
      properties:
        rank:
          type: integer
        participant:
          $ref: '#/components/schemas/ParticipantInfo'
        xp_score:
          type: integer
        is_anonymous:
          type: boolean

    MyRank:
      type: object
      properties:
        rank:
          type: integer
        xp_score:
          type: integer

    LeaderboardResponse:
      type: object
      properties:
        leaderboard:
          type: array
          items:
            $ref: '#/components/schemas/LeaderboardEntry'
        my_rank:
          $ref: '#/components/schemas/MyRank'
        total_participants:
          type: integer

    LeaderboardResponseWrapper:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/LeaderboardResponse'
